pipeline {
    agent {
        docker {
            image 'composer:latest'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sh 'ls -al'
                sh 'cat composer.json || echo "composer.json not found"'
            }
        }
        stage('Build') 
            steps {
                sh 'composer install'
            }
        }
        stage('Test') {
            steps {
                sh './vendor/bin/phpunit --log-junit logs/unitreport.xml -c tests/phpunit.xml tests'
            }
        }
    }
    post {
        always {
            junit 'logs/unitreport.xml'
        }
    }
}
